site_name: My Docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.social

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JiepengLab/notebook


nav:
- Home: index.md
- User Guide:
    - Writing your docs: user-guide/writing-your-docs.md
    - Styling your docs: user-guide/styling-your-docs.md
- About:
    - License: about/license.md
    - Release Notes: about/release-notes.md